### ISSUE TITLE
Generate reference tables

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#101]
I think the easiest way to get the functionality of https://github.com/ThreeSixtyGiving/standard/blob/master/tools/generate_reference_tables.py but for the new flatten-tool mutlisheet https://github.com/OpenDataServices/flatten-tool/issues/90 is going to be to adapt flatten-tool to produce those tables.

This may also help move us towards solving an OCDS use case which is generating a mapping template.

**Comment by Bjwebb** [comment]
There is now a branch for this, which is used to generate the tables in https://github.com/ThreeSixtyGiving/standard/blob/update-flattentool/documentation/reference.md

This code isn't really ready to be merged into master, as the extra functionality is included in a hacky way. Plan is to clean it up for inclusion in a future sprint.

**Comment by Bjwebb** [comment]
@timgdavies I've briefly got this code mostly working for the OCDS schema too (there seems to be problems with titles atm):
```
./flatten-tool create-template --output-format all --output-name ocds-reference-table --schema release-schema.json --main-sheet-name releases --use-titles --create-reference-tables
```

The output can be seen at:
https://docs.google.com/spreadsheets/d/1ibA0ssVh3X3ioAwoJ5tQHBIdZrT_3J6N6LnZvR_elks/edit#gid=2034539753

Hopefully this is useful to inform the discussion of what mapping templates we might want to generate.

**Comment by timgdavies** [comment]
Thanks @Bjwebb  - this is really helpful indeed. 

I think the titles issue *may* be due to a lot of missing titles in the OCDS Schema itself (this is something we need to look at in version 1.1). 

We're doing some learning about mapping templates with work for Mexico right now - so perhaps we can have a working session on this sometime soon - but this certainly gives me something to be going on with.

**Comment by jpmckinney** [comment]
I don't know that it should be flatten-tool's responsibility to create such tables. They can be generated easily enough when needed, and there are relatively few uses for such tables. I think it's better for flatten-tool to stay focused on `flatten` / `unflatten` and generating empty output from schema (`create-template`).

**Comment by duncandewhurst** [comment]
I think this need is now met by OCDS Kit's [mapping-sheet command](https://ocdskit.readthedocs.io/en/latest/cli/schema.html#mapping-sheet) and API, which can be used with any JSON Schema. Therefore, I'm going to close this issue and the linked PR. Feel free to reopen if I misunderstood.
