### ISSUE TITLE
OCDS organisations are not handled correctly as they don't have a simple `id` field

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#103]
Instead of `id` they have `identifier/scheme` and `identifier/id` https://github.com/open-contracting/standard/blob/1.0-dev/standard/schema/release-schema.json#L692

**Comment by Bjwebb** [comment]
@timgdavies Might be helpful for me to run this problem by you tomorrow. Main thing I want to establish at this point is whether there's anything relevant I should be suggesting for the upgrade process.

**Comment by Bjwebb** [comment]
classification also has `scheme` and `id`

**Comment by Bjwebb** [comment]
@timgdavies Is this mentioned somewhere in an OCDS standard issue?

**Comment by timgdavies** [comment]
Just checked and I don't think so. Can you quickly open an issue for it?

**Comment by Bjwebb** [comment]
Issue for this is at https://github.com/open-contracting/standard/issues/361

**Comment by timgdavies** [comment]
OCDS 1.1 added the required identifiers.
