### ISSUE TITLE
Remove code that's no longer used

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#111]
e.g. path_search ?

**Comment by threeaims** [comment]
@Bjwebb @kindly Actually, path_search() is used in `flattentool/json_input.py` `JSONInput`'s `parse()` method here:

https://github.com/OpenDataServices/flatten-tool/blob/master/flattentool/json_input.py#L84

These tests fail without it:

* `flattentool/tests/test_roundtrip.py` - `test_roundtrip_360()`
* `flattentool/tests/test_json_input.py` - `test_root_list_path()`

Shall we keep that particular one for now? There's plenty of other code I'm able to clean up.
