### ISSUE TITLE
Add ODS support

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#115]
This has been identified as a need for 360Giving.

**Comment by andylolz** [comment]
Doesn’t look like openpyxl has ODS support. But there’s [pyexcel-ods3](https://github.com/pyexcel/pyexcel-ods3)…

**Comment by andylolz** [comment]
ODS as an input and/or output format?

**Comment by andylolz** [comment]
(made a start on this at [andylolz/flatten-tool#ods-support](https://github.com/andylolz/flatten-tool/tree/ods-support))

**Comment by Bjwebb** [comment]
> ODS as an input format, output format, or both?

Ideally both.

**Comment by robredpath** [comment]
@jpmckinney I think the intention here is to facilitate use of `.ods` files instead of `.xlsx` files, and conversion of both to JSON (or vice-versa) rather than conversion between the two flat types. 

If someone wanted to publish using an open flat format (ie, `.ods`), we don't want to discourage that by requiring that they first convert to a less-open format before they can use our tooling. 

However, given the advanced age of this issue and lack of progress, I don't think it's going to be a priority.

**Comment by andylolz** [comment]
> less-open format

Happy to be corrected… But I’m not sure XLSX is actually a less-open format
https://en.wikipedia.org/wiki/Comparison_of_Office_Open_XML_and_OpenDocument

**Comment by jpmckinney** [comment]
Conversion would just be running one command before the flatten-tool command, which I don't think is a big enough barrier to discourage users. For LibreOffice users:

```
libreoffice --convert-to xlsx filename.ods
```

Or:

```
libreoffice --convert-to ods filename.xlsx

```

**Comment by Bjwebb** [comment]
@andylolz The standardisation of OOXML was very controversial at the time. e.g. https://arstechnica.com/uncategorized/2008/10/norwegian-standards-body-implodes-over-ooxml-controversy/ Many considered the spec large and bloated, and difficult to implement, and Microsoft Office's XLSX files don't necessarily follow exactly what it says.

**Comment by stevieflow** [comment]
In terms of input format , then ods is a standard adopted by UK Gov (alongside 360, IATI & OCDS!) - https://www.gov.uk/government/publications/open-standards-for-government/sharing-or-collaborating-with-government-documents - which is a driver to this issue

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write tests for flatten-tool .ods support + merge + deploy to CoVEs](https://trello.com/c/qDgyY63Z/4-write-tests-for-flatten-tool-ods-support-merge-deploy-to-coves)

**Comment by Bjwebb** [comment]
We now have .ods support.

**Comment by robredpath** [comment]
> We now have .ods support.

🎉
