### ISSUE TITLE
Documents, items and tenderers flatten to multiple sheets (#bug #ocds)

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/flatten-tool#132]
I noted a couple of issues with how the OCDS validator flattens documents and items [here](http://standard.open-contracting.org/validator/data/c8850106-9fdb-443c-956e-98073f967fdd)

**Documents**
The flattened xlsx file contains multiple sheets for documents:
- documents
- ten_documents
- con_documents
- awa_documents
- con_imp_documents
- pla_documents

Data is populated in the _documents_ sheet which has columns for documents from the _tender_, _award_ and _contract_ stages whilst the individual _xxx_documents_ tabs are empty.

**Items**
The flattened xlsx file contains multiple sheets for items:
- items
- awa_items
- con_items
- ten_items

Data is populated in the _items_ sheet which has columns for items from the _tender_ and _contract_ stages but **doesn't** have columns for items from the _award_ stage. _con_items_ and _ten_items_ are empty whilst In this example the source JSON data didn't include items at the _award_ stage so I'm not sure where that would flatten too.

**Tenderers**
The flattened xlsx file contains multiple sheets for tenderers:
- tenderers
- ten_tenderes

Data is populated in the _tenderers_ tab and _ten_tenderers_ is empty.

**Comment by Bjwebb** [comment]
This is fixed now on a branch. This is what the example data looks like when flattened: [flattened.xlsx](https://github.com/OpenDataServices/flatten-tool/files/1148123/flattened.xlsx). The documents tab is gone, and the individual ten_documents sheet is populated instead.

**Comment by duncandewhurst** [comment]
@Bjwebb looks good for ```ten_documents```, ```ten_items``` and ```ten_tenderers``` I would need to test with some more sample data to check the same for the other stages

**Comment by Bjwebb** [comment]
This is fixed on dev now, you can test it at http://release-201707.dev.cove.opendataservices.coop/validator/
