### ISSUE TITLE
Sort outputted XML according to an XML schema

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#146]
This is necessary for it to validate against a schema that uses sequences, such as the IATI one https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd

**Comment by timgdavies** [comment]
Is this possibly to abstract in a way that would also work for JSON schemas? 

For readability and easy scanning when reviewing data, it would be great if we could get OCDS etc. data out of a process sorted according to property orders in the schema...

**Comment by andylolz** [comment]
A couple of things to note:
 * IATI has multiple schemas (iati-common.xsd + iati-*-schema.xsd) so I suppose you’d need to be able to pass those into unflatten and the CLI (although for sorting, you can probably get away with ignoring iati-common.xsd)
 * unflatten already accepts a (JSON) schema, and uses it for column header lookups. So you could pass in the XML schema(s) as a separate parameter, or check the `xml` parameter and skip that stuff on True, or do the same thing for XML
 * the [code that does this in CoVE](https://github.com/OpenDataServices/cove/blob/ee291e0b121ca49818b27713ede74af1e2c0fd66/cove_iati/lib/iati_utils.py) is the sort of thing that should exist in a separate library. I’m surprised it doesn’t already exist elsewhere, but I wasn’t able to find a solution. But anyway – not sure about copying that code over here.
