### ISSUE TITLE
Do not hardcode iati-activities for top level for all xml.

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/flatten-tool#150]
https://github.com/OpenDataServices/flatten-tool/blob/master/flattentool/xml_output.py#L28

Would it make sense to be root_list_path or maybe some other special option for xml conversion.

**Comment by Bjwebb** [comment]
Yes. I think reusing root_list_path would be fine.

**Comment by Bjwebb** [comment]
Not hardcoding this makes sense. I'm not sure how's best to specify it, because root_list_path is already used for `iati-activity` (ie. the non-plural recurring element within `iati-activities`)

**Comment by andylolz** [comment]
> I'm not sure how's best to specify it, because root_list_path is already used for `iati-activity`

I think this is a) distinct from root_list_path, and b) XML-specific. So `--xml-root-path`?
