### ISSUE TITLE
Add note to docs about case insensitive file systems

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/flatten-tool#195]
Since d9e62653, this repo behaves a bit weirdly on a case insensitive file system. I wonder if this is worth noting in [the Getting Started docs](http://flatten-tool.readthedocs.io/en/latest/getting-started/#installation), because it’s a little bit unusual.

**Comment by Bjwebb** [comment]
I'm not sure I see anything about file names in that commit, so I don't know what this weird behaviour is.

**Comment by andylolz** [comment]
The commit adds the following files:
 * flattentool/tests/fixtures/xlsx/WellcomeTrust-grants_2_grants.xlsx
 * flattentool/tests/fixtures/xlsx/WellcomeTrust-grants_2_Grants.xlsx

These filenames differ by a single character – the ‘g’ in the final ‘grants’ is uppercase in one, and lowercase in the other.

**Comment by Bjwebb** [comment]
Aha. Perhaps best to rename one of those.
