### ISSUE TITLE
Add documentation for sheet configuration rows

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/flatten-tool#202]
I don’t think there’s documentation for hash directives like these:
https://github.com/OpenDataServices/flatten-tool/blob/f70c41484e1c5db152db3762de1a4667a1402140/flattentool/tests/fixtures/csv/commands_in_file/sheet1.csv#L1

I’m only aware of how to use them from reading tests (confirmation that tests > documentation!)

**Comment by Bjwebb** [comment]
Yeah, looks like the docs we do have are in the CoVE docs https://cove.readthedocs.io/en/latest/spreadsheet_input/

**Comment by andylolz** [comment]
> Yeah, looks like the docs we do have are in the CoVE docs

Ahhhh, interesting! Thanks for flagging, @Bjwebb.

I guess it should appear in both…?

**Comment by Bjwebb** [comment]
Yes, probably.

**Comment by jpmckinney** [comment]
I believe this is closed by #216.

**Comment by andylolz** [comment]
Agreed! Closing.
