### ISSUE TITLE
DeprecationWarning when generating xlsx

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/flatten-tool#205]
flatten-tool flatten --root-list-path=items -f=csv  standard/example1.json 

Is fine.

```
vagrant@ubuntu-xenial:/vagrant$ flatten-tool flatten --root-list-path=items -f=xlsx  standard/example1.json 
/vagrant/src/flattentool/flattentool/output.py:72: DeprecationWarning: Call to deprecated function remove_sheet (Use wb.remove(worksheet) or del wb[sheetname]).
  self.workbook.remove_sheet(self.workbook.active)

```

This is with openpyxl==2.5.3

**Comment by jpmckinney** [comment]
It was deprecated on the 2.4 branch https://bitbucket.org/openpyxl/openpyxl/commits/72475d22347a32e9c7237e67d7f0c9cb765c9d3f

So, should be safe to update, as we require >=2.5 in setup.py
