### ISSUE TITLE
Roll-up doesn't work with $ref fields

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/flatten-tool#209]
I've been trying to generate a template [from this schema](https://github.com/SocialEconomyDataLab/spec/blob/2e8ca1a537ceeae24bafb1ce7317776074c08416/schema/schema.json) with the command:

> flatten-tool create-template -s schema.json --rollup

and based on [these rollUp properties](https://github.com/SocialEconomyDataLab/spec/blob//2e8ca1a537ceeae24bafb1ce7317776074c08416/schema/schema.json#L55).

This throws the error:

>  UserWarning: fundingOrganization in rollUp but not in schema

which I believe is down to the fact that `fundingOrganization` field in the child object is itself a $ref value. 

Ideally $ref's should be resolved (following our non-JSON schema compliant pattern of allowing title, description etc. to override child properties) before the rollUp is performed if this is possible.

**Comment by Bjwebb** [comment]
flatten-tool does resolve refs before working with the schema. (Although not using our particular pattern - but I don't think that's the problem here).

I think something else odd is going on here.

**Comment by timgdavies** [comment]
Apologies for this issue. I worked out with a bit of testing that I needed to use the full path of the properties I was rolling up as here: https://github.com/SocialEconomyDataLab/spec/blob/revised-schema/schema/schema.json#L67

We might want to add this to the documentation, but no change to the code needed for this one.

**Comment by Bjwebb** [comment]
Glad that works. What stumps me is why that's true for this schema, but isn't true for the [360Giving schema](https://github.com/ThreeSixtyGiving/standard/blob/master/schema/360-giving-schema.json)
