### ISSUE TITLE
Making Creating Templates work with Open Ownership

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/flatten-tool#226]
This might be ok actually, but we will want to make sure it's documented in the Open Ownership page.

So apply the patch from part 1 of #225 so refs work and then run:

    flatten-tool  create-template -f csv -s bods-package.json -o template --root-id=statementID

And you get a blank output, as the tools doesn't like the whole list as a root element thing? But actually, maybe we want to do something different anyway. 

1) Run:

        flatten-tool  create-template -f csv -s ownership-or-control-statement.json -o template --root-id=statementID

2) Go to the template folder and add "ownershipOrControlStatement-" to the start of the new files.

3) Run:

        flatten-tool  create-template -f csv -s entity-statement.json -o template --root-id=statementID

4) Go to the template folder and add "entityStatement-" to the start of the **new** files.

5)  Run:

        flatten-tool  create-template -f csv -s person-statement.json -o template --root-id=statementID

4) Go to the template folder and add "personStatement-" to the start of the **new** files.

You now have a directory with a set of files that is a good template:

 *  entityStatement-addresses.csv
 *  entityStatement-annotations.csv
 *  entityStatement-identifiers.csv
 *  entityStatement-main.csv
 *  entityStatement-sou_assertedBy.csv
 *  ownershipOrControlStatement-annotations.csv
 *  ownershipOrControlStatement-interests.csv
 *  ownershipOrControlStatement-main.csv
 *  ownershipOrControlStatement-sou_assertedBy.csv
 *  personStatement-addresses.csv
 *  personStatement-annotations.csv
 *  personStatement-identifiers.csv
 *  personStatement-main.csv
 *  personStatement-names.csv
 *  personStatement-nationalities.csv
 *  personStatement-pepStatus.csv
 *  personStatement-sou_assertedBy.csv

The reasons why I think it's good to have separation is that now the 3 types are different, it's clear what sub sheet goes with which type and it's clear which columns to use on which types. (See #223 for more) 

It's true that some fields are repeated - "entityStatement-addresses.csv" and "personStatement-addresses.csv" are the same. But I think that's fine - the point of spreadsheets is for humans to work with and it's very clear to humans this way!

You can now add data to these sheets, and run unflatten to get JSON back!

**Example data**

entityStatement-main.csv
```
statementID,statementType,statementDate,entityType,missingInfoReason,name,alternateNames,incorporatedInJurisdiction/name,incorporatedInJurisdiction/code,foundingDate,dissolutionDate,uri,replacesStatements,source/type,source/description,source/url,source/retrievedAt
entity1,entityStatement,"2017-10-10",,"I don't care","Bobs Drink Store"
```
personStatement-addresses.csv
```
statementID,addresses/0/type,addresses/0/address,addresses/0/postCode,addresses/0/country
person1,home,"12 home street"
person1,work,"12 work street"
```

personStatement-main.csv

```
statementID,statementType,statementDate,personType,missingInfoReason,placeOfBirth/type,placeOfBirth/address,placeOfBirth/postCode,placeOfBirth/country,birthDate,deathDate,placeOfResidence/type,placeOfResidence/address,placeOfResidence/postCode,placeOfResidence/country,source/type,source/description,source/url,source/retrievedAt,replacesStatements
person1,personStatement,2019-10-10
```

**Run**

Apply #221 and run

    flatten-tool unflatten -f csv template/  -o template.json --no-root-list-path --id-name="statementID"

**Result**

```
[
    {
        "statementID": "entity1",
        "statementType": "entityStatement",
        "statementDate": "2017-10-10",
        "missingInfoReason": "I don't care",
        "name": "Bobs Drink Store"
    },
    {
        "statementID": "person1",
        "addresses": [
            {
                "type": "home",
                "address": "12 home street"
            },
            {
                "type": "work",
                "address": "12 work street"
            }
        ],
        "statementType": "personStatement",
        "statementDate": "2019-10-10"
    }
]
```

**Comment by jpmckinney** [comment]
Is this closed by #235 and #238?
