### ISSUE TITLE
Don't include empty sheets or columns

### ISSUE THREAD

**Issue by timgdavies** [OpenDataServices/flatten-tool#227]
In cases when generating flattened data driven by a schema you can end up with a **lot** of empty sheets when there are scheme elements not used. 

It would be good to have the option to tell flatten too to only include a column if has values, and only include a sheet if it has at least one column with a value in it. 

(i.e. This is essentially the output you get if you run flatten without the schema....) 

In particular, having this in CoVE (may need a separate issue) would be good.

**Comment by jpmckinney** [comment]
This will be closed by #241

**Comment by rhiaro** [comment]
Fixed by https://github.com/OpenDataServices/flatten-tool/pull/268
