### ISSUE TITLE
Is there an off by one error in headerrows, or does this just need documenting better?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/flatten-tool#230]
https://flatten-tool.readthedocs.io/en/latest/unflatten/#configuration-properties-skip-and-header-rows

Says: "headerrows - ignore the first n rows after the field paths"

Sounds great!

But if you look at the example sheet, it has "headerrows 3" but only 2 rows ... lines 5 and 6 in https://github.com/OpenDataServices/flatten-tool/blob/master/examples/cafe/skip-and-headers/data.csv

Whaa? I would expect "headerrows 2" in this case.

I just tried it with real code and got the same result. First I tried what I expected:

```
#,headerrows 1
statementID,statementType,statementDate,entityType,name,foundingDate
info
1dc0e987-5c57-4a1c-b3ad-61353b66a9b7,entityStatement,2017-11-18,registeredEntity,CHRINON LTD,2010-11-18

```

And I got an extra wrong bit in the output:
```
{
        "statementID": "info"
    },
```

Then I tried:

```
#,headerrows 2
statementID,statementType,statementDate,entityType,name,foundingDate
info
1dc0e987-5c57-4a1c-b3ad-61353b66a9b7,entityStatement,2017-11-18,registeredEntity,CHRINON LTD,2010-11-18
```

And it worked fine?

**Comment by andylolz** [comment]
Oh I see! You’re quite right. This line of documentation is wrong:

> headerrows - ignore the first n rows after the field paths

So maybe:

> headerrows - the total number of header rows. Note that the first row will be treated as field paths

…or something like that. It’s a bit clunky, but I guess it’s still probably preferable to fix the docs rather than to change how this works.

**Comment by odscjames** [comment]
>  I guess it’s still probably preferable to fix the docs rather than to change how this works.

Probably true

> headerrows - the total number of header rows. Note that the first header row will be treated as field paths.

Sounds good to me! Thanks
