### ISSUE TITLE
Add flattentool to pypi and change installation instructions to use pip

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#254]
This seems appropriate, now that the tool is versioned. `flattentool` is an available name on pypi.

**Comment by rhiaro** [comment]
It's been added to pip: https://pypi.org/project/flattentool/ but the installation instructions are not updated yet

**Comment by jpmckinney** [comment]
Closing as this is no longer an issue for me (feel free to re-open a new issue).
