### ISSUE TITLE
Consider renaming --remove-empty-schema-columns

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#271]
The name seems unclear, because schemas don't have columns (neither does JSON input data). 

Shouldn't it be something like exclude/omit/ignore blank/missing/unused, e.g. `--exclude-unused` or `--exclude-unused-schema-fields`?

Also, does the option make sense if no schema is specified? If not, then the help text should say so. The help text should also mention the omission of sheets (only mentions columns).

**Comment by jpmckinney** [comment]
cc @odscjames re: #268

**Comment by odscjames** [comment]
> Also, does the option make sense if no schema is specified? If not, then the help text should say so. The help text should also mention the omission of sheets (only mentions columns).

Good point, will do.

> The name seems unclear, because schemas don't have columns (neither does JSON input data).

No, but spreadsheets do and that's what is being dropped. And it's the column from the schema .... I chatted to folk here, and we think we're ok with the name. It's a complex operation, so it's always going to be hard to get a name that is clearly understood at first read. As long as we make sure it's very well documented both in the help and sphinx docs, that's the more important thing.
