### ISSUE TITLE
Broken in python 2.7?

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/flatten-tool#286]
Reported by @romifz

**Comment by kindly** [comment]
I think we need more specifics:

https://flatten-tool.readthedocs.io/en/latest/getting-started/?highlight=2.7#python-version-support

**Comment by romifz** [comment]
I found that my issue was with the OCDSKit and not with the flatten tool, I must have confused the documentation pages. Sorry for the confusion!

**Comment by jpmckinney** [comment]
OCDS Kit is only tested on Python 3.6 – no plans to support 2.7, which is almost a decade old.

**Comment by romifz** [comment]
I understand. It would be good though if we can state the Python required/tested version somewhere.

**Comment by jpmckinney** [comment]
Good idea – I've added a Python version badge to the readmes.
