### ISSUE TITLE
openpyxl 2.6.0 breaks Flatten-Tool!

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/flatten-tool#287]
Example: https://travis-ci.org/OpenDataServices/flatten-tool/builds/495995349

**Comment by odscjames** [comment]
We can fix this quickly by requiring 2.5 -  do we want to do this? See branch "fix-travis".

Making it work with both 2.5 and 2.6 might be difficult - would we need to make sure Travis ran tests against both versions?

**Comment by odscjames** [comment]
For now, Flatten-tool is locked to 2.5

But leaving this ticket open as we will have to deal with this at some point!

**Comment by Bjwebb** [comment]
The latest openpyxl release has a [useful fix for IATI CoVE](https://github.com/OpenDataServices/cove/issues/977#issuecomment-470455662), so it would be useful to upgrade to 2.6.1.  I'm happy to take a look into this at some point.

**Comment by Bjwebb** [comment]
I've fixed this in https://github.com/OpenDataServices/flatten-tool/pull/294, which requires `>=2.6` instead.
