### ISSUE TITLE
Flatten: Error or at least warn if there is no root-list-path key

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#292]
The docs have:

> If you forget the --root-list-path option and your data isn’t under a top level key called main, Flatten Tool won’t find your data and will instead generate a single empty sheet called main, which probably isn’t what you want.

This is a common gotcha. If `--root-list-path` isn't specified, I'd prefer an error if there is no `main` key. If `--root-list-path` is specified but there is no matching key, I can see an argument in favor of just issuing a warning instead of an error.

**Comment by jpmckinney** [comment]
Noting that if the input is an array (i.e. --root-is-list) then using --root-list-path will cause no output (or warnings) to be written (but it will still take a very long time to run).

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make selected improvements to flatten-tool's UI](https://trello.com/c/JrUdKojd/89-make-selected-improvements-to-flatten-tools-ui)

**Comment by jpmckinney** [comment]
Closing as this is no longer an issue for me (feel free to re-open a new issue).
