### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#299]
We already discourage the use of Python 2.

At some point, we will want to drop it entirety. This is most likely to be due to a dependency we use dropping Python 2 support  - openpyxl 3.0 and py.test 5.0 both plan to do this.

**Comment by michaelwood** [comment]
Now that Python 2 (as of Jan 2020) is officially EOL it seems as good a time as any to drop support for Python 2. 

Related #328

**Comment by odscjames** [comment]
Agreed.

@jpmckinney Do you know if this would cause any issues for OCDS users?

**Comment by jpmckinney** [comment]
I don’t know any specific cases; all OCDS tools in OCP repos are Python 3. They can still install old versions if they are stuck on Python 2, at least. I’d drop support.

**Comment by odscjames** [comment]
Merged to Master, will be in next release
