### ISSUE TITLE
Translation support: Use translated code titles for code values

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#307]
… if `--schema` is provided. This can either be the default behavior of --use-titles, or an additional flag.

**Comment by duncandewhurst** [comment]
Worth noting that this will break round tripping the data

**Comment by jpmckinney** [comment]
Can't we have a parallel flag to convert code titles back to codes? We have `--use-titles` on the `flatten` command and `--convert-titles` on the `unflatten` command to preserve round-tripping.

We might need another flag to set the path to the codelists directory (unless we assume that the codelists directory is relative to the path given by `--schema`).

**Comment by kindly** [comment]
My preference for this would be some kind of preprocessing of the JSON before flattentool sees it that could built into ocdskit and also for the reverse.

I worry about putting too many features like this into flattentool as it is centralising a point of failure and error reporting; invalid codelists, codelists that are now not web accessable, codelist caching for speed need to be considered.

Also fairly open-contracting specific things will need to be considered e.g codelists in extensions.

Also having a more usable JSON representation would also benefit analysts who want to use JSON as the input format.

**Comment by duncandewhurst** [comment]
Noting my other concern which we discussed on our call:

Some publishers use flatten-tool in their publication process and adding this feature could result in 'source' OCDS data which uses code titles rather than codes, which would then be incompatible with other OCDS tools, methodologies etc.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/ocdskit/issues/96

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flatten Tool: Support translation of sheet names](https://trello.com/c/m5zFMCSy/233-flatten-tool-support-translation-of-sheet-names)
