### ISSUE TITLE
Error with date placement

### ISSUE THREAD

**Issue by mrshll1001** [OpenDataServices/flatten-tool#308]
From the OCDS CRM
> Hello. From the data expedition we saw with the Chileans a possible error
in the flatten tool. Apparently the tool is putting under
tender/tenderperiod the dates from tender/enquiryperiod.
> 
> Could we check that please? It came up in the datasets that Romina
prepared.

**Comment by jpmckinney** [comment]
This issue can be closed, as it could not be reproduced, per updates in CRM.
