### ISSUE TITLE
.ods Last Modified column does not convert correctly

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#342]
The best example I can find of this is the Wiltshire Community Foundation spreadsheets from http://data.threesixtygiving.org/
Download one of these as xlsx, and use Libre Office to convert it to an .ods

The xlsx passes validation: https://dataquality.threesixtygiving.org/data/b647b3df-ff14-4d83-9080-25631a829df5
The .ods does not: https://dataquality.threesixtygiving.org/data/bb4587f4-f6c2-45ed-8939-f95b7c621571

This is due to the Last Modified column, which becomes dateModified in the json.

In the json converted from the xlsx:
``` json
"dateModified": "2017-09-14T00:00:00+00:00"
```

In the json converted from the ods
```json
"dateModified": "2017-09-14":
```

There's a work around, which is to modify the time e.g. add a second "01" instead "00".
Additionally, the column is optional, so can just be removed.

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [.ods Last Modified column does not convert correctly](https://trello.com/c/VsQ9vYgJ/44-ods-last-modified-column-does-not-convert-correctly)

**Comment by robredpath** [comment]
Is it possible to fix this at source - ie, for the user in LibreOffice?

**Comment by Bjwebb** [comment]
In the libreoffice UI, it appears to be a datetime.
