### ISSUE TITLE
Numbers formatted with commas in .ods files break the conversion

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#343]
e.g. Quixote Foundation spreadsheets from http://data.threesixtygiving.org/ converted to .ods in LibreOffice

https://dataquality.threesixtygiving.org/data/8bb8b710-7e07-4ddd-9c68-4651294af815

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [.ods formatted numbers bug](https://trello.com/c/7kSacVa2/39-ods-formatted-numbers-bug)

**Comment by robredpath** [comment]
```
 Sorry, we can't process that data

We think you tried to supply a spreadsheet, but we failed to convert it.

Error message: ValueError("could not convert string to float: '2,000.00 '",)
```
