### ISSUE TITLE
Dependencies with Django

### ISSUE THREAD

**Issue by aguilerapy** [OpenDataServices/flatten-tool#363]
https://github.com/OpenDataServices/flatten-tool/blob/2667a7ae5caf5fb1976b7964f03e0d16be37459a/flattentool/i18n.py#L9

This new file imports `django`, but dependencies and requirements were not updated causing this error when importing `flatten-tool`:

![imagen](https://user-images.githubusercontent.com/48607824/96624431-1d193700-12e3-11eb-96f9-69dd5f265f3c.png)

**Comment by Bjwebb** [comment]
The django import should be optional, but it looks like there's another error when we try to catch the ImportError. This should be fixed in the latest version 0.15.1
