### ISSUE TITLE
Flattening a list of lists

### ISSUE THREAD

**Issue by duncandewhurst** [OpenDataServices/flatten-tool#398]
I'm trying to flatten this [file](https://gist.github.com/duncandewhurst/8b901036e8c0b261246b06dbfc904ed8) using the following command: `flatten-tool flatten -f xlsx example.json`. However, the resulting xlsx file is empty.

Flattening the nodes list with `flatten-tool flatten -f xlsx --root-list-path nodes example.json` works OK. However, flattening the links list with `flatten-tool flatten -f xlsx --root-list-path links example.json` returns an error: 'list' object has no attribute 'items'.

I think this is because `links.location.geometry.coordinates` is a list of lists (the list in the actual file is longer):

```json
{
  "links": [
    {
       "location": {
          "coordinates": [
              [
                26.081,
                -24.406
              ],
              [
                26.081,
                -24.406
              ]
           ]
        }
     }
  ]
}
```

**Comment by Bjwebb** [comment]
Yes, it looks like we lack support for flattening of lists of lists. Here's a TODO in the code https://github.com/OpenDataServices/flatten-tool/blob/main/flattentool/json_input.py#L422 !

It should be fairly easy to implement this, to produce a cell with the contents `26.081,-24.406;26.081,-24.406`. @duncandewhurst is that what you expect?

**Comment by duncandewhurst** [comment]
Thanks, @Bjwebb. I was expecting something like `[26.081;-24.405]; [26.09; -24.416]` but your suggestion looks easier to work with.

We've yet to decide whether we're going to use Flatten Tool for Open Fibre (see https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/14) so no need to implement this yet.

**Comment by Bjwebb** [comment]
For info, my suggestion is based on what we already support for unflattening (which I think requires a schema).

**Comment by duncandewhurst** [comment]
@Bjwebb we've decided to use Flatten Tool for the Open Fibre alpha, would you have time to implement this before you go on leave?

**Comment by Bjwebb** [comment]
I've made a PR for this https://github.com/OpenDataServices/flatten-tool/pull/401

**Comment by duncandewhurst** [comment]
Closing as the PR is merged.
