### ISSUE TITLE
Remove OCDS specific aspects of the code

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#40]
- [x] OCID ID
- Top schema dict is assumed to be object (dictionary), but some JSON files will have a list as the root (split out to #47 as it doesn't affect 360 Giving)
- [x] Outputted JSON has `base['releases']` populated, and this is hardcoded.
- [x] OCDS specific defaults https://github.com/open-contracting/flattening-ocds/issues/34
- Default for root-id, see below

**Comment by practicalparticipation** [comment]
For use in other projects it should be possible to specify:

(a) The root sheet (e.g --root=grants / --root=release) 

(b) The root ID (e.g. --root-id=ocid / --root-id=id)

And the root sheet name should be used in the outputted JSON (as in base['releases'] or base['grants'])

**Comment by Bjwebb** [comment]
Does the 360 giving standard have a "root ID" in the same way that open contracting does? In open contracting, each release has an `id`, in addition to the `ocid`, whereas a 360Giving activity just has an `id`.

**Comment by Bjwebb** [comment]
I already have `main-sheet-name` for the root sheet name. I'm now using this supplied value as the key that's used for the top level JSON.

Let me know if you want me to also rename `main-sheet-name`.

**Comment by practicalparticipation** [comment]
--main-sheet-name works well for me.

**Comment by practicalparticipation** [comment]
In response to question on root ID, 360 Giving just has an ```id``` field for each Activity. There is no equivalent of the separate ```ocid``` and ```id``` found in OCDS.

**Comment by Bjwebb** [comment]
I've added the `--root-id` flag. For 360 Giving, you would use `--root-id=''`

**Comment by Bjwebb** [comment]
I think the current behaviour of `root-id`, and particularly the defaulting to `ocid` is confusing, and we should look to update this. The default should be like 360Giving, where there is no special ID, and there should be an extra argument if we need it for OCID.

However, I'm not sure if we should be special casing the OCID for releases at all. Since "A release ID must be unique within a release-package", I think it should be sufficient to merge based only on the ID, and treat the OCID as an ordinary field.

**Comment by Bjwebb** [comment]
Discussed this with @kindly this morning: the problem with merging only based on ID, is that flatten-tool may not be dealing with the contents of a release package (and instead e.g. the output of an ID)

**Comment by timgdavies** [comment]
If there are non-backward compatible changes to OCDS which might help here - do shout.

**Comment by Bjwebb** [comment]
I've changed the defaults now to be less ocds specific, but the ocds case still uses the ocid.

I think the change to OCDS that would make this easier would be to require that IDs be globally unique - which is a tighter constraint than what's being suggested for 1.1 in https://github.com/open-contracting/standard/issues/246#issuecomment-220613523
