### ISSUE TITLE
optional geo dependencies, no documentation

### ISSUE THREAD

**Issue by odscjen** [OpenDataServices/flatten-tool#445]
As per [this changelog entry](https://github.com/OpenDataServices/flatten-tool/blob/main/CHANGELOG.md#0240---2023-11-15) the WKT support is now optional rather than default but all you get when converting geodata is the following warning message

> UserWarning: Install flattentool's optional geo dependencies to use geo features

But there's nothing in the flatten-tool documentation that I could see that says how to do this. 

This came about when [running `manage.py pre-commit` as part of OFDS development](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html).

**Comment by jpmckinney** [comment]
The warning can add, e.g. `..., for example: pip install flattentool[geo]`

**Comment by Bjwebb** [comment]
This is now implemented in https://pypi.org/project/flattentool/0.26.0/
