### ISSUE TITLE
Allow header row to use titles rather than field names

### ISSUE THREAD

**Issue by practicalparticipation** [OpenDataServices/flatten-tool#45]
The [360 Giving Data Standard](https://threesixtygiving.github.io/standard/) makes use of user-friendly field titles, as opposed to field names, as column headings. 

To allow 360 Giving Data to be converted by the tool we either need:

(a) A process that runs to convert the header row from field titles to field names prior to flattening / unflattening;

(b) The tool to be able to read field titles rather than field names;

**Comment by Bjwebb** [comment]
Two example commands using titles to create a template, and unflatten, are now in the README https://github.com/open-contracting/flattening-ocds/blob/master/README.md#360-giving-support
