### ISSUE TITLE
Use custom exceptions instead of ValueError

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#450]
For example:

https://github.com/OpenDataServices/flatten-tool/blob/1d1c662cd01916078fe401895bf8c4ddb6f176bd/flattentool/input.py#L1010-L1018

This will allow other tools to disambiguate errors raised by Flatten Tool from other errors (e.g. unexpected exceptions).

**Comment by Bjwebb** [comment]
This is now implemented in https://pypi.org/project/flattentool/0.26.0/
