### ISSUE TITLE
Use custom warnings

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#451]
`DataErrorWarning` is used in some places. The package should define its own `class FlattenToolWarning(UserWarning)` and have `DataErrorWarning` subclass it. `FlattenToolWarning` can be used for all other warnings if you don't want to invent further subclasses. This will make it easier to disambiguate warnings within flatten-tool, and between other sources.

**Comment by Bjwebb** [comment]
This is now implemented in https://pypi.org/project/flattentool/0.26.0/
