### ISSUE TITLE
Formula rather than value being read from Excel cells

### ISSUE THREAD

**Issue by practicalparticipation** [OpenDataServices/flatten-tool#49]
If a cell contains a formula then that is being read into the JSON conversion rather than the calculated value of the cell.

The details at https://stackoverflow.com/questions/22613272/how-to-access-the-real-value-of-a-cell-using-the-openpyxl-module-for-python suggest this should be possible to change using the data_only=True flag when opening the workbook.

**Comment by practicalparticipation** [comment]
Needs full testing - but worked for me on a quick test.

**Comment by Bjwebb** [comment]
Looks good to me. I've added a unit test for it too.
