### ISSUE TITLE
Only titles of fields including in RollUp in schema converted to fieldnames in JSON

### ISSUE THREAD

**Issue by practicalparticipation** [OpenDataServices/flatten-tool#50]
For example, if the schema for recipient organisation includes:

```json
  "recipientOrganization": {
      "items": {
        "$ref": "#/definitions/Organization"
      },
      "type": "array",
      "description": "-",
      "weight": 5,
      "title": "Recipient Org",
      "rollUp": ["id","name","charityNumber","companyNumber","streetAddress","addressLocality","postalCode","description","url"]      
    },
```

And a table row includes:

|Recipient Org:Street Address | Recipient Org:City | Recipient Org:County | Recipient Org:Postal Code|Recipient Org:Country|
|----|---|---|---|---|
|383-387 High Street|Stratford| |E15 4QZ|UK|

Then this will be converted to:

```json
"recipientOrganization": [
                {
                    "name": "Discover", 
                    "charityNumber": 1070468, 
                    "addressLocality": "Stratford", 
                    "streetAddress": "383-387 High Street", 
                    "postalCode": "E15 4QZ", 
                    "id": "GB-CHC-1070468"
                }
            ],
           "Recipient Org": {
                "Country": "UK"
            },
```

Because ```country``` is not included in the schema Roll Up, and so it is not interpreted as a title alias for a field name, but instead as an additional field provided by the publisher.

This is not the desired behaviour, as we want to allow that publishers might practice a different set of roll ups in their own files in order to meet local use-cases.

I.e. The roll up specification in the schema should be used to determine:

(a) The creation of templates
(b) The creation of canonical summary spreadsheets

But should not limit the range of ways in which a publisher might express child fields in the main spreadsheet row.

**Comment by Bjwebb** [comment]
This is now fixed on a branch, and is available for testing in Cove at http://flatten-tool-updates.dev.cove.opendataservices.coop/360/
