### ISSUE TITLE
flatten-ocds command doesn't output help information on python2

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#52]
(but does on Python 3)

**Comment by Bjwebb** [comment]
As for https://github.com/OpenDataServices/flatten-tool/issues/79#issuecomment-224935105, I suggest we decide that Python 2 is less well supported, state this in the README, and then close this issue.

**Comment by Bjwebb** [comment]
README updated https://github.com/OpenDataServices/flatten-tool#python-version-support. Issue closed and python2-wontfix label added.

**Comment by andylolz** [comment]
This seems to work as expected for python 2.7. And python <2.7 isn’t supported anyway.

I suggest removing the `python2-wontfix` label (so this issue doesn’t show up when users click through from docs).
