### ISSUE TITLE
README doesn't tell you what this code does

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/flatten-tool#64]
While there is a lot of useful information in the README file, it doesn't actually tell you what this code does/is supposed to do, and what for.

**Comment by timgdavies** [comment]
I've run a first pass of writing a more detailed README

This could be improved with examples, and perhaps some documentation would belong in the long-run on the Wiki.

**Comment by Bjwebb** [comment]
Further tasks:
- [ ]  Description of what the column headers look like in the template (general form and what information is annotated etc.) (from https://github.com/OpenDataServices/flatten-tool/issues/31)
- [ ] Write some general documentation of how the new json pointer and multi-sheet approach work. Adding images or tables of spreadsheets, and the corresponding output to the README would be good.  https://github.com/OpenDataServices/flatten-tool/issues/90

**Comment by Bjwebb** [comment]
We're setting up Sphinx docs to allow us to write more in depth documentation, and pull in function description from the code etc.

**Comment by jpmckinney** [comment]
This issue is quite old, and the docs have improved since then. I think it can be closed, and more specific issues (of which some already exist) can be created in follow-up.

**Comment by odscjames** [comment]
+1 on closing this.
