### ISSUE TITLE
Integer in spreadsheet should be integer (not decimal) in the unflattened JSON

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#72]
(Originally reported at https://github.com/OpenDataServices/cove/issues/93)

CSV example: https://gist.github.com/stevieflow/bbb25e5368eb34f8d6f1
XLSX example: http://www.wolfson.org.uk/media/2741/wolfson-foundation-grants-2014.xlsx

**Comment by stevieflow** [comment]
I think this also applies to a .xlsx file:

http://www.wolfson.org.uk/media/2741/wolfson-foundation-grants-2014.xlsx

http://dev.cove.opendataservices.coop/360/data/182f642b-be72-4ada-8aa8-7e6aa12b4d70

**Comment by Bjwebb** [comment]
Thanks @stevieflow, looks like it is both. Have updated the issue to reflect that.

**Comment by Bjwebb** [comment]
I think the issue here is probably that we're wrapping everything in `Decimal` as discussed yesterday.

This should be covered by @threeaims' suggested change if we make sure to not wrap ints in addition to floats.

**Comment by Bjwebb** [comment]
@stevieflow This is now fixed on dev, e.g. http://dev.cove.opendataservices.coop/360/data/d5572032-42e5-437c-bed3-6ba76bbefb13

**Comment by stevieflow** [comment]
Great news - thanks
