### ISSUE TITLE
Newest openpyxl doesn't handle a sheet with a single cell properly

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#78]
See https://github.com/OpenDataServices/flatten-tool/commit/e0ecec379a1e313666da7a5f1e511b8ca6cd0d0c#diff-21ce1ab676e420986beb88a25b47c1fbL47 for the changes I had to make to some of the tests to get them to work.

I think in practice this isn't much of an issue, because there's no reason for people to have a sheet with just one cell populated.

**Comment by robredpath** [comment]
Closing - this is definitely an edge case that we're unlikely to ever hit in practical usage at the scales that we're likely to see in the coming months. If anyone hits this in real usage, please re-open this issue so that we can look at getting it fixed!
