### ISSUE TITLE
Titles support is broken for Open Contracting

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#84]
The generated template has "Open Contracting ID" instead of `ocid`, but unflattening still expects `ocid`.

**Comment by timgdavies** [comment]
Related to #40. Would be fixed if we switch to remove special casing of ocid in our flatten approach.

**Comment by jpmckinney** [comment]
Seems to have been fixed and issue can be closed:

```bash
curl -O https://raw.githubusercontent.com/open-contracting/standard/1.1-dev/standard/docs/en/examples/tender.json
flatten-tool flatten --use-titles -root-list-path releases -s path/to/release-schema.json tender.json
flatten-tool unflatten --convert-titles -s path/to/release-schema.json -f csv flattened
```

`ocid` round-trips without issue.

**Comment by robredpath** [comment]
Great, thanks @jpmckinney
