### ISSUE TITLE
Types from the schema should be used

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/flatten-tool#85]
E.g. if the schema says something should be a string, we should convert values to string. This would prevent this issue https://github.com/OpenDataServices/cove/issues/267

**Comment by ekoner** [comment]
This issue also happens with charity and company number. I've added a demonstrator file.

**Comment by Bjwebb** [comment]
This should be fixed by https://github.com/OpenDataServices/flatten-tool/pull/89

A test copy of Cove is at 
http://flatten-tool-updates.dev.cove.opendataservices.coop/ 

I'm not sure where to find the demonstrator file, but a spreadsheet I found on plan.io by searching this issue URL looks to be fixed (once the main sheet is named grants).
